""" BWDT Constants """

# Images to pull when syncing the registry
IMAGES = [
    'kolla/ubuntu-source-neutron-server',
    'kolla/ubuntu-source-neutron-openvswitch-agent',
    'kolla/ubuntu-source-neutron-dhcp-agent',
    'kolla/ubuntu-source-neutron-l3-agent',
    'kolla/ubuntu-source-neutron-metadata-agent',
    'kolla/ubuntu-source-heat-api',
    'kolla/ubuntu-source-heat-engine',
    'kolla/ubuntu-source-heat-api-cfn',
    'kolla/ubuntu-source-nova-compute',
    'kolla/ubuntu-source-nova-novncproxy',
    'kolla/ubuntu-source-nova-ssh',
    'kolla/ubuntu-source-nova-placement-api',
    'kolla/ubuntu-source-nova-api',
    'kolla/ubuntu-source-nova-consoleauth',
    'kolla/ubuntu-source-nova-conductor',
    'kolla/ubuntu-source-keystone-ssh',
    'kolla/ubuntu-source-nova-scheduler',
    'kolla/ubuntu-source-keystone',
    'kolla/ubuntu-source-keystone-fernet',
    'kolla/ubuntu-source-cinder-volume',
    'kolla/ubuntu-source-cinder-api',
    'kolla/ubuntu-source-cinder-scheduler',
    'kolla/ubuntu-source-glance-api',
    'kolla/ubuntu-source-openvswitch-db-server',
    'kolla/ubuntu-source-openvswitch-vswitchd',
    'kolla/ubuntu-source-kolla-toolbox',
    'kolla/ubuntu-source-fluentd',
    'kolla/ubuntu-source-memcached',
    'kolla/ubuntu-source-nova-libvirt',
    'kolla/ubuntu-source-keepalived',
    'kolla/ubuntu-source-chrony',
    'kolla/ubuntu-source-mariadb',
    'kolla/ubuntu-source-haproxy',
    'kolla/ubuntu-source-iscsid',
    'kolla/ubuntu-source-rabbitmq',
    'kolla/ubuntu-source-cron'
]
